import Link from "next/link";

export default function Privacy() {
  return (
    <section id="privacy-policy" className="section-pp" aria-labelledby="pp-title">
      <div className="mavii_wrap">
        <header className="pp-hero">
          <h1 id="pp-title" className="pp-title">Privacy Policy</h1>
          <p className="pp-lead">
            Maviimedia is a Mumbai- and Pune-based branding & product studio serving clients worldwide,
            fusing strategy, design, and engineering to deliver modern websites, custom software and SaaS,
            AI-powered applications, and end-to-end product design. We move from brief to launch with speed
            and rigor, building experiences that are beautiful, reliable, and measurable.
          </p>
          <p className="pp-meta">
            <strong>Effective:</strong> September 19, 2026 • <strong>Last Updated:</strong> September 19, 2026
          </p>
        </header>

        <nav className="pp-toc" aria-label="Table of contents">
          <ul>
            <li><a href="#who-we-are">1. Who We Are</a></li>
            <li><a href="#scope">2. Scope</a></li>
            <li><a href="#data-we-collect">3. Data We Collect</a></li>
            <li><a href="#how-we-use">4. How We Use Data</a></li>
            <li><a href="#legal-bases">5. Legal Bases (GDPR/UK GDPR)</a></li>
            <li><a href="#cookies">6. Cookies & Tracking</a></li>
            <li><a href="#ai">7. AI, Models & Client Content</a></li>
            <li><a href="#sharing">8. Sharing & Disclosures</a></li>
            <li><a href="#retention">9. Retention</a></li>
            <li><a href="#transfers">10. International Transfers</a></li>
            <li><a href="#security">11. Security</a></li>
            <li><a href="#your-rights">12. Your Rights</a></li>
            <li><a href="#children">13. Children</a></li>
            <li><a href="#changes">14. Changes</a></li>
            <li><a href="#contact">15. Contact</a></li>
          </ul>
        </nav>

        <section id="who-we-are" className="pp-section">
          <h2>1) Who We Are</h2>
          <p>
            “Maviimedia” (“we”, “us”, “our”) is a design & engineering studio headquartered in Mumbai and Pune, India.
            We partner with founders, marketing teams, and product leaders to plan, design, build, and grow digital
            experiences. For website visitors and prospects, we typically act as a <em>data controller</em>; for client
            projects, we may operate as a <em>processor</em> under a services agreement or data processing addendum (“DPA”).
            This Policy explains the types of information we handle, the purposes for which we process it, and the choices
            available to you.
          </p>
          <p>
            We value clarity and restraint: we only collect data we actually need, limit access to those who require it,
            and build processes that prefer privacy by default. Wherever possible, we favor configuration over collection,
            aggregation over identification, and short retention over indefinite storage.
          </p>
        </section>

        <section id="scope" className="pp-section">
          <h2>2) Scope</h2>
          <p>
            This Policy applies to personal data we process when you browse our websites, submit a form, request a proposal,
            subscribe to updates, apply for a role, participate in research or testing, use our hosted tools, or interact
            with us via email, phone, or social channels. It also covers logs and telemetry generated by our products or
            prototypes that we host. It does not apply to client-owned products where we act solely as a processor and where
            the client’s privacy terms govern the service.
          </p>
          <p>
            Where we link to third-party services (e.g., payment, analytics, scheduling), their privacy practices apply.
            We encourage you to read those notices, as we don’t control their independent processing.
          </p>
        </section>

        <section id="data-we-collect" className="pp-section">
          <h2>3) Data We Collect</h2>
          <p>
            We collect information in three ways: (a) directly from you, (b) automatically via your device and our services,
            and (c) from third-party sources that help us operate our business. Categories include:
          </p>
          <ul className="pp-list">
            <li><strong>Identity & Contact:</strong> name, company, role, email, phone, country/time zone. Used to respond, scope projects, and communicate.</li>
            <li><strong>Business Context:</strong> briefs, requirements, assets, design copy, feedback, and support tickets that you choose to share for scoping and delivery.</li>
            <li><strong>Usage & Device:</strong> IP address, approximate location, device/browser type, OS, language, pages viewed, session timing, referring URLs, and basic interaction events to understand performance and usability.</li>
            <li><strong>Account & Product (if applicable):</strong> login identifiers, role/permissions, feature usage, preferences, audit logs, and support interactions for any hosted tools we provide.</li>
            <li><strong>Payment (if applicable):</strong> we rely on PCI-compliant providers to handle payments; we receive limited billing metadata (e.g., last 4 digits, status) and do not store full card numbers.</li>
            <li><strong>Recruitment:</strong> CV/resume, portfolio links, public profiles, interview notes, and assessment results shared during hiring.</li>
            <li><strong>Third-Party Sources:</strong> analytics, communications, error monitoring, and CRM systems that help us maintain service quality and continuity.</li>
          </ul>
        </section>

        <section id="how-we-use" className="pp-section">
          <h2>4) How We Use Data</h2>
          <p>
            We process personal data to operate, secure, and improve our services; to communicate with you; and to meet legal
            obligations. Typical uses include responding to enquiries, preparing proposals, executing statements of work,
            providing onboarding and support, monitoring reliability and abuse, and measuring effectiveness of features or
            content. We also use aggregated insights to inform product direction and design decisions.
          </p>
          <p>
            Marketing is light-touch: occasional newsletters, case studies, launches, or invites—always with a clear opt-out.
            Where consent is required (e.g., non-essential cookies), we will seek it before processing.
          </p>
        </section>

        <section id="legal-bases" className="pp-section">
          <h2>5) Legal Bases (GDPR/UK GDPR)</h2>
          <p>
            Our legal bases include <strong>Contract</strong> (to deliver requested services), <strong>Legitimate Interests</strong>
            (to secure systems, understand performance, and operate responsibly without overriding your rights), <strong>Consent</strong>
            (for optional analytics/marketing), and <strong>Legal Obligation</strong> (for tax, accounting, and compliance).
            Where we rely on legitimate interests, we apply balancing tests and safeguards such as minimization, access
            controls, and short retention.
          </p>
        </section>

        <section id="cookies" className="pp-section">
          <h2>6) Cookies & Tracking</h2>
          <p>
            We use essential cookies to keep the site functioning (e.g., load balancing, session continuity) and—where legally
            required, with your consent—analytics/performance cookies to understand traffic and improve UX. You can manage
            preferences via your browser or our banner (if displayed). Blocking non-essential cookies may reduce certain
            features, but core content should remain accessible.
          </p>
          <p>
            We do not use fingerprinting or invasive tracking. If we run A/B tests or heatmaps, we configure them to avoid
            capturing sensitive inputs and to retain data for limited durations.
          </p>
        </section>

        <section id="ai" className="pp-section">
          <h2>7) AI, Models & Client Content</h2>
          <p>
            We respect client IP and confidentiality. We do <strong>not</strong> use client-provided content to train public
            or third-party foundational models unless a contract or explicit written instruction permits it. When we use AI
            services as processors—for example, to draft summaries, classify feedback, or assist support—we apply data
            minimization, scoping, and role-based access. Where possible, we disable training on our business data and
            restrict retention to short windows.
          </p>
          <p>
            Prompt logs and outputs may be reviewed by authorized team members to improve reliability and safety, subject to
            contractual commitments. We encourage clients to mark and route sensitive datasets through agreed secure channels.
          </p>
        </section>

        <section id="sharing" className="pp-section">
          <h2>8) Sharing & Disclosures</h2>
          <p>
            We share personal data with vendors that help us operate our services—cloud infrastructure, email and messaging,
            analytics, error monitoring, logging, payments, scheduling, and document storage. These processors are bound by
            contracts and may only process data as instructed by us. We may disclose information to comply with law, protect
            rights and safety, or in connection with a merger, acquisition, or asset transfer (with notice where required).
          </p>
          <p>
            On request, and where appropriate, we can provide a current list of sub-processors for a given engagement.
          </p>
        </section>

        <section id="retention" className="pp-section">
          <h2>9) Retention</h2>
          <p>
            We retain personal data only for as long as necessary to fulfill the purposes described in this Policy, comply
            with legal obligations, resolve disputes, and enforce agreements. In practice, we prefer short retention with
            regular reviews. When information is no longer required, we delete it or irreversibly de-identify it according
            to our data retention schedule and backup rotation.
          </p>
        </section>

        <section id="transfers" className="pp-section">
          <h2>10) International Transfers</h2>
          <p>
            We operate globally and may transfer data to countries with different data protection laws. Where we do so, we
            rely on appropriate safeguards—such as Standard Contractual Clauses (SCCs) or other lawful transfer mechanisms—
            and assess vendors for technical and organizational measures that protect your data during and after transfer.
          </p>
        </section>

        <section id="security" className="pp-section">
          <h2>11) Security</h2>
          <p>
            We employ layered security controls including encryption in transit, access control and least privilege,
            environment segregation, secrets management, monitoring, and incident response procedures. While no system can
            be perfectly secure, we aim for practical resilience: fast detection, bounded blast radius, and clear recovery
            paths. We periodically review vendors and update controls based on changes in risk.
          </p>
        </section>

        <section id="your-rights" className="pp-section">
          <h2>12) Your Rights</h2>
          <p>
            Depending on where you live, you may have rights to access, correct, delete, restrict, or object to processing;
            to receive a portable copy; and to withdraw consent where processing is based on consent. Residents of the EU/UK
            (GDPR), India (DPDP Act, 2023), and California (CPRA) have additional rights specific to their jurisdictions.
            We will verify your request to a reasonable standard and respond within the timelines set by law. You may also
            use an authorized agent where permitted.
          </p>
          <p>To exercise rights, see <a href="#contact">Contact</a>. We will explain any limits that apply (e.g., legal retention).</p>
        </section>

        <section id="children" className="pp-section">
          <h2>13) Children</h2>
          <p>
            Our services are intended for business users and are not directed to children below the age defined by local
            law (e.g., 13 or higher). We do not knowingly collect such data. If you believe a child has provided personal
            information, please contact us so we can delete it.
          </p>
        </section>

        <section id="changes" className="pp-section">
          <h2>14) Changes to This Policy</h2>
          <p>
            We may update this Policy from time to time. Material changes will be highlighted on this page with a revised
            “Last Updated” date. If you continue to use our services after the update, you agree to the revised terms as
            permitted by law.
          </p>
        </section>

        <section id="contact" className="pp-section">
          <h2>15) Contact</h2>
          <p>
            Questions, requests, or complaints? Email us at{" "}
            <a href="mailto:support@maviimedia.com">support@maviimedia.com</a>
            {" "}or write to our India office (Mumbai/Pune). EU/UK residents may also contact their local supervisory authority.
            For India DPDP, you may contact our Grievance Officer (details to be published here if required).
          </p>
          <p className="pp-note">If we appoint a Data Protection Officer (DPO) or EU/UK representative, we will add those details here.</p>
        </section>

        <p className="pp-disclaimer">
          <em>Note:</em> This notice is general information, not legal advice. Where this notice conflicts with a signed
          contract or DPA, the contract controls.
        </p>
      </div>
    </section>
  );
}